### ISSUE TITLE
Unable to upload golang results

### ISSUE THREAD

**Issue by Milerius** [report-ci/scripts#8]
Hello i have some problem to upload golang result, the script said i have no result available

<img width="1680" alt="Capture d’écran 2019-07-07 à 21 58 37" src="https://user-images.githubusercontent.com/21139416/60773206-7ebf8d00-a102-11e9-9b68-7e28bc3b46a8.png">

**Comment by Milerius** [comment]
with configuration:

```yaml
language: go

go:
  - 1.12.x

before_install:
  - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
  - sudo apt-get update
  - sudo apt install python3.6 -y

script:
  - go test -json ./... > tests_log.json

after_script:
  - curl -s https://report.ci/upload.py | python3.6 - --include='*.json' --framework=go

```

https://travis-ci.com/Milerius/komodo-ecosysboard/jobs/213830642
